### PR TITLE
Initial 2024 website update

### PR DESCRIPTION
**Pull request by JamesAllingham**
I made the following changes:

- Copied last year's site to a '2023' folder. Fixed some links that broke as a result. (These files can mostly be ignored I think).
- Updated all of the dates, etc. (2023 -> 2024, 5th -> 6th). 
- Updated the organizers list.
- Disabled (for now) the accepted papers, program committee, and schedule pages.
- Removed (for now?) the sponsors.
- Added the call for papers for the extended abstract and archival tracks. Didn't yet add details for the fast track since there didn't seem to be a consensus for how that should work. 
- Updated the latex template (2023 -> 2024, 5th -> 6th).

### CODE REVIEW

**Comment by wiseodd** [comment]
It seems that the website is already hosted on Github Pages? 
https://github.com/approximateinference/approximateinference/deployments?environment=github-pages#activity-log

**Comment by wiseodd** [comment]
In the tex template, `AABI 2023` should be `AABI 2024`:
```
\jmlrproceedings{AABI 2023}{6th Symposium on Advances in Approximate Bayesian Inference, 2024}
```

**Comment by wiseodd** [comment]
I think we should rename the files in the paper template from `jmlr-sample.*` to `aabi2024.*` or similar.

**Review by wiseodd — CHANGES_REQUESTED** [review]
See my comments

**Comment by wiseodd** [comment]
Proposal for `css/main.css`:

```
ul.flex-column {
  list-style-position: inside !important;
}
ol, ul:not(.flex-column) {
  padding-left: 2.5em !important;
}
```

instead of 

```
ul {
  list-style-position: inside !important;
}
```

Nicer IMO, and more in line with what you'd expect in e.g. Google docs, LaTeX, etc. (This will make the nav area on the left unchanged.)

Screenshot 2024-01-21 at 9 06 20 AM

**Comment by wiseodd** [comment]
The commit above is to make the list of organizers nicer, esp. for the "Advisory Committee" subsection.

Screenshot 2024-01-21 at 9 19 53 AM

**Comment by wiseodd** [comment]
@JamesAllingham I'm done reviewing. Thanks for the work!

**Comment by JamesAllingham** [comment]
> It seems that the website is already hosted on Github Pages? https://github.com/approximateinference/approximateinference/deployments?environment=github-pages#activity-log

We'll have to clarify the situation with Javi, but I am fairly certain that approximateinference.org is pointed at Dustrin's server. I tried to access approximateinference.github.io and it doesn't seem to be live.

**Comment by wiseodd** [comment]
> > It seems that the website is already hosted on Github Pages? https://github.com/approximateinference/approximateinference/deployments?environment=github-pages#activity-log
> 
> We'll have to clarify the situation with Javi, but I am fairly certain that approximateinference.org is pointed at Dustrin's server. I tried to access approximateinference.github.io and it doesn't seem to be live.

You can access it at <http://approximateinference.github.io/approximateinference/>. However, you'll be redirected to <http://approximateinference.org> which is the one on Dustin's server. But the fact that that github.io page exists seems to mean that there's already a deployment workflow on Github Pages. Looking forward to hearing Javi's clarification.

**Comment by wiseodd** [comment]
The mobile view looks good! However, it introduces quite a whitespace on top when viewed on desktop:

Screenshot 2024-01-25 at 12 41 02 PM

**Comment by wiseodd** [comment]
Maybe arrange "Home", "Call", "Sponsors" horizontally?

**Pull request merged**
